name: pubglobalupdate
version: 1.0.1
description: Helper to update global activated packages, all at once or by package name
homepage: https://github.com/tekartik/pubglobalupdate.dart

environment:
  sdk: ^3.7.0

dependencies:
  args: '>=2.5.0 <4.0.0'
  process_run: '>=1.0.0+1 <2.0.0'
  pub_semver: '>=2.1.4 <4.0.0'
  path: '>=1.9.0 <3.0.0'
  yaml: '>=3.1.2 <5.0.0'
dev_dependencies:
  lints: '>=4.0.0'
  dev_build: '>=1.0.0+7'
  test: '>=1.25.8'

executables:
  pubglobalupdate:
